#!/usr/bin/env bash
set -euo pipefail

repo=$1
container=${2:-$1}
containerWithoutSlashes=${container##*/}

docker build --build-arg "GITHUB_REPOSITORY=$repo" -t "ghcr.io/$repo/$containerWithoutSlashes:latest" .
docker push "ghcr.io/$repo/$containerWithoutSlashes:latest"

echo ""
echo "now open https://github.com/$repo/pkgs/container/$containerWithoutSlashes/} and give write permissions"
